# Generated by Django 3.2 on 2021-05-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField(max_length=300)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.ukvisitorguide.cn%2Fwp-content%2Fuploads%2F2015%2F11%2FFood-placeholder.jpg&f=1&nofb=1', max_length=500)),
            ],
        ),
    ]
